// 🍽 Kitchen phase 4 (2026-10-02): scaling, favorites rotation, library filter, first-run card.
const fs=require("fs"); const src=fs.readFileSync(__dirname+"/index.html","utf8");
let pass=0, fail=0; const ok=(n,c)=>{ if(c){pass++;console.log("  ok  - "+n);} else {fail++;console.log("  FAIL- "+n+(arguments.length>2?"":""));} };
const fn=name=>{ const a=src.indexOf("function "+name+"("); if(a<0) throw new Error("missing "+name); let i=src.indexOf("{",a), d=0, j=i; for(;j<src.length;j++){ if(src[j]==="{")d++; else if(src[j]==="}"){ d--; if(!d) break; } } return src.slice(a,j+1); };
const glyph=src.match(/const KIT_FRAC_GLYPH=\{[^}]+\};/)[0];
const L=new Function(glyph+fn("kitQtyParse")+fn("kitQtyFmt")+fn("kitScaleLine")+fn("kitFavRank")+fn("kitFavWeeks")+"; return {kitScaleLine,kitFavRank,kitFavWeeks};")();
const S=L.kitScaleLine; const eq=(a,b,n)=>{ const r=S(a[0],a[1]); ok(n+": "+JSON.stringify(a[0])+" ×"+a[1]+" → "+JSON.stringify(r), r===b); };
eq(["2 cups flour",2],"4 cups flour","whole number");
eq(["1/2 tsp salt",2],"1 tsp salt","fraction");
eq(["1 1/2 cups milk",2],"3 cups milk","mixed number");
eq(["½ cup oil",3],"1 ½ cup oil","glyph");
eq(["1.5–2 lb salmon fillets",2],"3–4 lb salmon fillets","decimal range");
eq(["3 eggs",0.5],"1 ½ eggs","halving");
eq(["2lb carrots",2],"4lb carrots","no space before unit");
eq(["olive oil",2],"olive oil","no amount → unchanged");
eq(["1 lemon, garlic powder, dill",2],"2 lemon, garlic powder, dill","only the leading amount");
eq(["12 tortillas",1.5],"18 tortillas","10+ rounds to whole");
eq(["2 cups flour",1],"2 cups flour","1× unchanged");
const meals={a:{name:"Tacos",ratings:{taylor:"love",caleb:"love"}},b:{name:"Chili",ratings:{taylor:"like"}},c:{name:"Liver",ratings:{taylor:"no",caleb:"love"}},d:{name:"Ziti",ratings:{andrew:"love"}},e:{name:"Soup"}};
const ids=L.kitFavRank(meals);
ok("favorites: ranked by votes, won't-eat outweighs a love, unrated left out", JSON.stringify(ids)===JSON.stringify(["a","d","b"]));
const wk=L.kitFavWeeks(ids,4,id=>meals[id].name);
ok("favorites: 4 weeks × 7 dinners", wk.length===4&&wk.every(w=>w.length===7&&w.every(d=>d.d)));
const flat=wk.flat().map(d=>d.d); ok("favorites: never the same dinner two nights running", flat.every((x,i)=>i===0||x!==flat[i-1]));
ok("scaling is display-only (the recipe text is never rewritten)", !/kitMeals\[[^\]]+\]\.ing\s*=/.test(fn("kitSetScale")+fn("kitScaleLine")));
ok("first-run card hides once recipes, a planned week and a rotation exist", /if\(steps\.every\(x=>x\[0\]\)\) return "";/.test(fn("kitStartHTML")));
ok("library rows carry their id so the search box filters without a repaint", /data-kit-mid=/.test(src)&&/querySelectorAll\('\[data-kit-mid\]'\)/.test(fn("kitLibFilter")));
ok("favorites rotation is saved as one path", /db\.ref\('kitchen\/rotations\/'\+id\)\.set\(rot\)/.test(fn("kitRotFromFavorites")));
console.log(pass+" passed, "+fail+" failed"); process.exit(fail?1:0);
